//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_Cells
    {
        public int id { get; set; }
        public string name { get; set; }
        public string ip { get; set; }
        public int port { get; set; }
    }
}
