//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBed
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipees
    {
        public string id { get; set; }
        public double max_heat { get; set; }
        public double min_heat { get; set; }
        public double opt_heat { get; set; }
        public double max_humidity { get; set; }
        public double min_humidity { get; set; }
        public double opt_humidity { get; set; }
        public double opt_light_hour { get; set; }
        public double end_time { get; set; }
    }
}
